const data = {
  products: [
    {
      id: 1,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/1000.png",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 3000,
      oldPrice: 5000,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Men",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 2,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/2000.png",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 2500,
      oldPrice: 7000,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Men",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 3,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/31.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 4500,
      oldPrice: 8500,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Men",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 4,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/41.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 7500,
      oldPrice: 10000,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Men",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 5,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/51.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 980,
      oldPrice: 1350,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Men",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 6,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/61.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 6400,
      oldPrice: 9600,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Men",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 7,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/71.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 5180,
      oldPrice: 7400,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Women",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 8,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/81.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 2600,
      oldPrice: 3000,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Women",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 9,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/91.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 7450,
      oldPrice: 8320,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Women",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 10,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/111.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 4900,
      oldPrice: 6900,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Women",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 11,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/121.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 6500,
      oldPrice: 7800,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Women",
      pickedFrom: "Gnena Mall",
    },
    {
      id: 12,
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      productImg: "img/131.jpeg",
      brandImg: "img/addidas.svg",
      imgIcon: "img/360.svg",
      rate: 4,
      currentPrice: 960,
      oldPrice: 1500,
      currency: "LE",
      sale: 30, //if sale < 0 hidden
      gender: "Women",
      pickedFrom: "Gnena Mall",
    },
  ],
  category: [
    {
      id: 1,
      gender: "Men",
      imgCate: "img/cate1.png",
    },
    {
      id: 2,
      gender: "Women",
      imgCate: "img/cate2.png",
    },
    {
      id: 3,
      gender: "Children",
      imgCate: "img/cate3.png",
    },
    {
      id: 4,
      gender: "Men",
      imgCate: "img/cate1.png",
    },
    {
      id: 5,
      gender: "Women",
      imgCate: "img/cate2.png",
    },
    {
      id: 6,
      gender: "Children",
      imgCate: "img/cate3.png",
    },
  ],
  offers: [
    {
      id: 1,
      title: "Valentine’s Day Discounts",
      caption: "Up to 70% sale on selected items during February.",
      imgOffer: "img/collection2.png",
    },
    {
      id: 2,
      title: "Men’s Fashion Discounts",
      caption: "Up to 50% sale on selected items during February.",
      imgOffer: "img/collection2.png",
    },
    {
      id: 3,
      title: "Valentine’s Day Discounts",
      caption: "Up to 70% sale on selected items during February.",
      imgOffer: "img/collection2.png",
    },
    {
      id: 4,
      title: "Men’s Fashion Discounts",
      caption: "Up to 50% sale on selected items during February.",
      imgOffer: "img/collection2.png",
    },
  ],
};

export default data;
